services:
  loja-db:
    image: mysql:8.4
    container_name: loja-db-banco
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: loja-app
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: loja
    ports:
      - "3306:3306"
    volumes: 
      - meus_dados:/var/lib/mysql
      - ./database/bd.sql:/docker-entrypoint-initdb.d/bd.sql:ro
  
  loja-api:
    build: ./backend
    image: loja-api-imagem
    container_name: loja-api-container
    ports:
      - "3000:3000"
    depends_on:
      - loja-db
  
  #loja-front:
  #  build: ./frontend
  #  image: loja-front-imagem
  #  container_name: loja-front-container
  #  ports:
  #    - "5173:5173"
  #  depends_on:
  #    - loja-api
volumes:
  meus_dados: